# MIT License
#
# Copyright (c) 2024 Zerocracy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: 'judges-action'
description: >
  This action will handle the deployment process of Judger-Action to GitHub Pages.
  It will run the "judges" tool to perform various checks and validations on the 
  project, update the project status, and complete the deployment process.'
author: 'Yegor Bugayenko <yegor256@gmail.com>'
runs:
  using: 'docker'
  image: 'docker://yegor256/judges-action:latest'
inputs:
  token:
    description: >
      Authentication token from www.zerocracy.com. This token is used to authenticate
      the user or the CI/CD pipeline with Zerocracy to enable deployment processes.
      It is crucial for the security and integrity of the deployment process, ensuring
      that only authorized users can initiate deployments.
    required: true
  options:
    description: >
      Command line options for the "judges" tool. This allows users to customize the
      behavior of the judges tool by passing various command line arguments. These
      options can include configurations for deployment, specific checks to be performed,
      or any other parameters supported by the judges tool.
    required: false
  verbose:
    description: >
      Log as much debug information as possible. When enabled, this option increases
      the verbosity of the logs generated by the action. This is useful for debugging
      purposes or when more detailed information about the deployment process is needed.
      It can help in identifying issues or understanding the deployment flow.
    required: false
    default: false
  factbase:
    description: >
      Path of the factbase file (also the name of the job in Zerocracy). This file
      contains essential data used by the judges tool during the deployment process.
      The factbase file should be located in the repository and its path correctly
      specified here. It plays a critical role in the operation of the judges tool,
      providing it with the necessary information to perform its tasks.
    required: true
    default: 'default.fb'
  cycles:
    description: >
      How many update cycles to run (keep it under 10). This is the number of update
      cycles that the judges tool will run before completing the deployment process.
      Each update cycle involves fetching the latest facts about the project, performing
      various checks and validations, and updating the project status accordingly.
      The number of cycles can be customized based on the project requirements and
      the desired level of automation. 
    required: true
    default: 5
